### PR TITLE
Added missing data

### PR DESCRIPTION
**Pull request by krishnaglodha**
2 datasets were missing 
1. countries shape file 
2. stadium.csv 
both files are added

### CODE REVIEW

**Review by justb4 — CHANGES_REQUESTED** [review]
Thanks, there are still some items to be addressed, see #85 and #86.
- remove `stadium.csv` from under `content/notebooks`
- populated-places shapefile is still missing, or can you use the version already under `content/data/shape`?
- ch7 the location for ipyleaflet: lat/lon should be reversed to denote Florence, so I think:

```
center = (43.7782731, 11.247928)
m = Map(center=center, zoom=17, close_popup_on_click=False)
marker = Marker(location=( 43.7782731, 11.247928,))
```

-

**Comment by krishnaglodha** [comment]
fixed following things 
1. added all missing data
2. checked entire visualisation and vector data file line by line and fixed small bugs
3. fixed all 3 issues mentioned in PR 
4. fixed issue https://github.com/geopython/geopython-workshop/issues/96

**Review by justb4 — CHANGES_REQUESTED** [review]
Thanks for this, did not have time to check everything.

One major: the Shape files in this PR will add about 70MB data to the repo. That is about the size of the entire current repo including all history.  Can you slim these files down?

**Comment by justb4** [comment]
Also: can you merge with upstream, there seem to be conflicts in Ch4 en Ch7.

**Comment by krishnaglodha** [comment]
I've merged files @justb4

**Comment by tomkralidis** [comment]
+1 for keeping the file sizes small.  We should either provide smaller / thinned out data or specify for download external to the repository.

**Comment by justb4** [comment]
Like I said in the Gitter chat, simply download the lowres (110m) versions, order of 120kb, they work as well:
https://www.naturalearthdata.com/downloads/110m-cultural-vectors/
Downloading during the workshop won't work in the MyBinder version as there is no local environment.

**Comment by justb4** [comment]
So once the smaller versions of the files are in this PR we may merge and then fix the outstanding other problems.

**Comment by justb4** [comment]
Also Ch7 from this PR works completely (in Docker version) with the smaller NE files: https://www.naturalearthdata.com/downloads/110m-cultural-vectors/

**Comment by justb4** [comment]
Offcourse in Ch4 and Ch7 text change `ne_10m_...` with `ne_110m_..`.

**Comment by krishnaglodha** [comment]
I have replaced populated shapefile (70MB) with Geojson ( 18 MB ) and it's references

**Comment by krishnaglodha** [comment]
> Like I said in the Gitter chat, simply download the lowres (110m) versions, order of 120kb, they work as well: https://www.naturalearthdata.com/downloads/110m-cultural-vectors/ Downloading during the workshop won't work in the MyBinder version as there is no local environment.

Sorry, I just saw this. 
I have made another commit by replacing geojson with this 1.8MB file

**Comment by justb4** [comment]
looking again : think all data is already in the repo: countries and populated_places. So the Shapefiles in this PR are not needed. 
Have little time today going to SOTM,, but the workshop needs to be ready and working. 
There is also still a  10m Shape 8MB in this PR.

I propose: can you make a new PR with just the Ch4 and Ch7 Notebooks? I merge and fix/add datafiles where needed. Think only the CSVs. All other NE data is already there in various formats. Again no need for the Shapefiles. @tomkralidis

**Pull request closed without merging**
