### PR TITLE
Update data analysis

### PR DESCRIPTION
**Pull request by francbartoli**
Update data analysis

### CODE REVIEW

**Comment by tomkralidis** [comment]
merging (will help review)

**Comment by francbartoli** [comment]
Thanks @tomkralidis

**Comment by tomkralidis** [comment]
Merged -- thanks @francbartoli !  cc @justb4 / @ldesousa @kalxas for us to review

**Comment by justb4** [comment]
Nice localized updates!

One editorial: line 146: `p = figure(title='Bucharest 226 dobson'` must be `p = figure(title=' Rio Gallegos 493 dobson'`

**Pull request merged**
